version: '3'
services:
  aiagent:
    build: .
    volumes:
      - ./src:/app/src
    depends_on:
      - ollama
    networks:
      - ai_network
    stdin_open: true  # This is equivalent to -i
    tty: true         # This is equivalent to -t

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - ai_network

networks:
  ai_network:

volumes:
  ollama_data: